#!/usr/bin/python

import sys, os

#See if we are running uninstalled
dname = os.path.dirname(__file__)
if os.path.basename(dname) == 'scripts':
    print 'Running uninstalled'
    sys.path.insert(0, os.path.join(os.path.abspath(dname), '..'))

import garmon.application


garmon.application.main()


